intentionally fail

diff --git a/charts/helloworld/templates/job.yaml b/charts/helloworld/templates/job.yaml
--- a/charts/helloworld/templates/job.yaml
+++ b/charts/helloworld/templates/job.yaml
@@ -3,6 +3,8 @@ apiVersion: v1
 data:
   script.sh: |-
     echo "RUNNING TEST"
+    echo "FAIL"
+    exit 1
     echo "TEST Passed"
     echo "{{ .Values.COUNTRY }}-prod"
     git clone https://github.com/michaelperel/config.git
