FAIL ON PURPOSE

diff --git a/charts/helloworld/templates/job.yaml b/charts/helloworld/templates/job.yaml
--- a/charts/helloworld/templates/job.yaml
+++ b/charts/helloworld/templates/job.yaml
@@ -2,7 +2,10 @@
 apiVersion: v1
 data:
   script.sh: |-
+    set -e
     echo "RUNNING TEST"
+    echo "FAILING ON PURPOSE"
+    exit 1
     echo "TEST Passed"
     echo "{{ .Values.COUNTRY }}-prod"
     git clone https://github.com/michaelperel/config.git
